// Invalid addition error

function start(in: ) out : no {
    integer a = 10 + "foo";

}

/*
    assert(throw(InvalidAdditionError))
*/